#!/bin/sh
export HOME=/var/lib/couchdb
export ERL_FLAGS="-couch_ini /usr/lib/couchdb/etc/default.ini /etc/couchdb/datadirs.ini /etc/couchdb/local.ini"

mkdir -p /var/run/couchdb
chown couchdb /var/run/couchdb
chown -R couchdb /etc/couchdb
exec chpst -u couchdb:couchdb /usr/lib/couchdb/bin/couchdb -r 5 -o /dev/null  -e /dev/null
